name: pageres
base: core18
version: git
summary: Capture website screenshots
description: |
  Capture screenshots of websites in various resolutions. A good way to make 
  sure your websites are responsive. It's speedy and generates 100 screenshots 
  from 10 different websites in just over a minute. It can also be used to 
  render SVG images.
  Usage:
    $ pageres <url> <resolution>

grade: stable
confinement: strict

parts:
  pageres:
    plugin: nodejs
    source: .
    nodejs-version: 14.15.3
    nodejs-package-manager: npm
    stage-packages:
      - ca-certificates
      - fonts-liberation
      - libatomic1
      - libnspr4
      - libnss3
      - xdg-utils

apps:
  pageres:
    extensions: [gnome-3-28]
    command: bin/pageres
    plugs: [home, network, browser-support]
